AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  AudioToText:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: AudioToText/audio_to_text.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: .debug/
  ExtractMedicalEntities:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: ExtractMedicalEntities/extract_medical_entities.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: .debug/
  SendEmail:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: SendEmail/lambda_function.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: .debug/
      Environment:
        Variables:
          SSM_PS_APPCONFIG_PATH: '/AppointmentConcierge'
